"""
AgentFinance v5 - Signal Model

Represents trading signals generated by the system.
"""

from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, ForeignKey, DateTime
from sqlalchemy.orm import relationship

from app.database import Base


class Signal(Base):
    """
    Signal model representing trading signals.
    
    Attributes:
        id: Primary key
        strategy_id: Foreign key to strategies table
        agent_id: Foreign key to agents table
        sector: Market sector (forex, commodities, stocks, indices, crypto)
        symbol: Trading symbol (e.g., "EURUSD", "XAUUSD")
        direction: Signal direction (buy, sell, neutral)
        confidence: Confidence score (0-100)
        status: Signal status (pending, active, expired, executed)
        created_at: Timestamp when signal was created
    """
    __tablename__ = "signals"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_id = Column(Integer, ForeignKey("strategies.id"), nullable=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=True)
    sector = Column(String(20), nullable=False)  # forex, commodities, stocks, indices, crypto
    symbol = Column(String(20), nullable=False)
    direction = Column(String(10), nullable=False)  # buy, sell, neutral
    confidence = Column(Float, nullable=True)  # 0-100
    status = Column(String(20), default="pending", nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    strategy = relationship("Strategy", back_populates="signals")
    agent = relationship("Agent", back_populates="signals")
    trades = relationship("Trade", back_populates="signal", lazy="dynamic")
    
    def __repr__(self):
        return f"<Signal(id={self.id}, symbol='{self.symbol}', direction='{self.direction}', confidence={self.confidence})>"
    
    def to_dict(self):
        """Convert signal to dictionary."""
        return {
            "id": self.id,
            "strategy_id": self.strategy_id,
            "agent_id": self.agent_id,
            "sector": self.sector,
            "symbol": self.symbol,
            "direction": self.direction,
            "confidence": self.confidence,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }