#!/usr/bin/env python3
"""
AgentFinance v3 — PostgreSQL Database Setup
Creates the trading data schema for signal history, performance tracking,
and market data persistence.

Usage:
    python3 setup_database.py              # Interactive setup
    python3 setup_database.py --init      # Initialize schema
    python3 setup_database.py --seed      # Add sample data
    python3 setup_database.py --status     # Show connection status
    python3 setup_database.py --migrate   # Run migrations

Requirements:
    PostgreSQL 14+ running locally or via Docker
    psycopg2: pip install psycopg2-binary
"""

import os
import sys
import json
import logging
import argparse
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, List, Dict, Any
from dataclasses import dataclass

# Add project root
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)8s] %(name)s: %(message)s",
)
log = logging.getLogger("db_setup")

# Colors
GREEN = "\033[0;32m"
RED = "\033[0;31m"
YELLOW = "\033[1;33m"
BLUE = "\033[0;34m"
NC = "\033[0m"


def print_ok(text: str):
    print(f"{GREEN}✓ {text}{NC}")


def print_fail(text: str):
    print(f"{RED}✗ {text}{NC}")


def print_warn(text: str):
    print(f"{YELLOW}⚠ {text}{NC}")


def print_info(text: str):
    print(f"{BLUE}ℹ {text}{NC}")


# ============================================================================
# SCHEMA DEFINITION
# ============================================================================

SCHEMA_SQL = """
-- AgentFinance v3 Database Schema
-- Generated: {timestamp}

-- ============================================================================
-- EXTENSIONS
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";  -- For fuzzy text search

-- ============================================================================
-- ENUMS
-- ============================================================================
CREATE TYPE trade_direction AS ENUM ('BUY', 'SELL');
CREATE TYPE order_status AS ENUM ('PENDING', 'OPEN', 'FILLED', 'PARTIAL', 'CANCELLED', 'REJECTED');
CREATE TYPE setup_type AS ENUM ('ORDER_BLOCK', 'BREAK_OF_STRUCTURE', 'CHANGE_OF_CHARACTER',
    'LIQUIDITY_SWEEP', 'DISPLACEMENT', 'INVERTED', 'MTS', 'FVG', 'MIXED');
CREATE TYPE session_name AS ENUM ('SYDNEY', 'TOKYO', 'LONDON', 'FRANKFURT', 'NY', 'SYDNEY_CLOSED');
CREATE TYPE timeframe_enum AS ENUM ('M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1', 'W1');

-- ============================================================================
-- CORE TABLES
-- ============================================================================

-- Trading signals generated by the SMC/technical engines
CREATE TABLE signals (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol          VARCHAR(12) NOT NULL,
    direction       trade_direction NOT NULL,
    setup_type      setup_type NOT NULL,
    timeframe       timeframe_enum NOT NULL,
    confidence      DECIMAL(4,2) CHECK (confidence BETWEEN 0 AND 1),
    entry_zone      JSONB,                    -- {min, max, ideal} price levels
    stop_loss       DECIMAL(12,5) NOT NULL,
    take_profit     JSONB NOT NULL,           -- [{level, type}, ...]
    risk_reward     DECIMAL(6,2),
    market_context  JSONB,                    -- session, trend, volatility
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    source          VARCHAR(50) DEFAULT 'smc_pipeline',

    -- Indexes
    CONSTRAINT signals_symbol_timeframe_check
        CHECK (symbol ~ '^[A-Z]{3}[A-Z]{3}$' OR symbol ~ '^[A-Z]{2}[A-Z]{3}$')
);
CREATE INDEX idx_signals_symbol ON signals(symbol);
CREATE INDEX idx_signals_created ON signals(created_at DESC);
CREATE INDEX idx_signals_setup ON signals(setup_type);
CREATE INDEX idx_signals_confidence ON signals(confidence DESC);

-- Executed trades (orders that were sent to cTrader)
CREATE TABLE trades (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    signal_id          UUID REFERENCES signals(id) ON DELETE SET NULL,
    order_id           VARCHAR(64),                     -- cTrader order ID
    position_id         VARCHAR(64),                     -- cTrader position ID
    symbol             VARCHAR(12) NOT NULL,
    direction          trade_direction NOT NULL,
    volume             DECIMAL(10,4) NOT NULL,
    entry_price        DECIMAL(12,5),
    exit_price         DECIMAL(12,5),
    stop_loss          DECIMAL(12,5),
    take_profit        DECIMAL(12,5),
    status              order_status DEFAULT 'PENDING',
    pnl                DECIMAL(12,2),
    pnl_pips           DECIMAL(10,2),
    commission          DECIMAL(10,4) DEFAULT 0,
    swap_cost           DECIMAL(10,4) DEFAULT 0,
    execution_mode     VARCHAR(20) DEFAULT 'live',      -- live, dry_run, backtest
    executed_at        TIMESTAMPTZ,
    closed_at          TIMESTAMPTZ,
    notes              TEXT,
    metadata           JSONB,
    created_at         TIMESTAMPTZ DEFAULT NOW(),
    updated_at         TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_trades_symbol ON trades(symbol);
CREATE INDEX idx_trades_status ON trades(status);
CREATE INDEX idx_trades_executed ON trades(executed_at DESC);
CREATE INDEX idx_trades_signal ON trades(signal_id);

-- Position snapshots for equity tracking
CREATE TABLE equity_snapshots (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    account_id  VARCHAR(32) NOT NULL,
    balance     DECIMAL(14,2) NOT NULL,
    equity      DECIMAL(14,2) NOT NULL,
    margin      DECIMAL(14,2) DEFAULT 0,
    margin_level DECIMAL(8,2),
    open_pnl    DECIMAL(12,2) DEFAULT 0,
    closed_pnl  DECIMAL(12,2) DEFAULT 0,
    snapshot_at TIMESTAMPTZ DEFAULT NOW(),
    trade_ids   UUID[]                              -- Array of open trade IDs
);
CREATE INDEX idx_equity_account ON equity_snapshots(account_id);
CREATE INDEX idx_equity_time ON equity_snapshots(snapshot_at DESC);

-- Market data OHLCV storage (for backtesting)
CREATE TABLE ohlcv_data (
    id          BIGSERIAL PRIMARY KEY,
    symbol      VARCHAR(12) NOT NULL,
    timeframe   timeframe_enum NOT NULL,
    open_time   TIMESTAMPTZ NOT NULL,
    close_time  TIMESTAMPTZ NOT NULL,
    open        DECIMAL(12,5) NOT NULL,
    high        DECIMAL(12,5) NOT NULL,
    low         DECIMAL(12,5) NOT NULL,
    close       DECIMAL(12,5) NOT NULL,
    volume      DECIMAL(16,4),
    tick_volume BIGINT,
    spread      DECIMAL(8,3),
    UNIQUE(symbol, timeframe, open_time)
);
CREATE INDEX idx_ohlcv_symbol_tf ON ohlcv_data(symbol, timeframe, open_time DESC);
CREATE INDEX idx_ohlcv_open_time ON ohlcv_data(open_time DESC);

-- Performance metrics by day/week/month
CREATE TABLE performance_metrics (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    period          VARCHAR(10) NOT NULL,           -- 'day', 'week', 'month'
    period_start    DATE NOT NULL,
    period_end      DATE NOT NULL,
    total_trades    INTEGER DEFAULT 0,
    winning_trades  INTEGER DEFAULT 0,
    losing_trades   INTEGER DEFAULT 0,
    win_rate        DECIMAL(6,3),
    avg_win         DECIMAL(12,2),
    avg_loss        DECIMAL(12,2),
    profit_factor   DECIMAL(8,3),
    max_drawdown    DECIMAL(8,3),
    sharpe_ratio    DECIMAL(8,3),
    total_pnl       DECIMAL(14,2),
    best_trade      DECIMAL(12,2),
    worst_trade     DECIMAL(12,2),
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(period, period_start)
);
CREATE INDEX idx_perf_period ON performance_metrics(period, period_start DESC);

-- Session analysis results
CREATE TABLE session_analysis (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session         session_name NOT NULL,
    date            DATE NOT NULL,
    session_start   TIMESTAMPTZ,
    session_end     TIMESTAMPTZ,
    high            DECIMAL(12,5),
    low             DECIMAL(12,5),
    range_pips      DECIMAL(10,2),
    close_position  VARCHAR(10),                   -- UPPER, LOWER, MIDDLE
    kill_zone_bias  VARCHAR(10),                    -- BULLISH, BEARISH, NEUTRAL
    setups_triggered INTEGER DEFAULT 0,
    setups_won      INTEGER DEFAULT 0,
    setups_lost      INTEGER DEFAULT 0,
    notes           TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(session, date)
);
CREATE INDEX idx_session_session ON session_analysis(session, date DESC);

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_trades_updated
    BEFORE UPDATE ON trades
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Calculate P&L from trade
CREATE OR REPLACE FUNCTION calculate_pnl(
    p_direction trade_direction,
    p_entry DECIMAL,
    p_exit DECIMAL,
    p_volume DECIMAL,
    p_pip_value DECIMAL DEFAULT 10.0,
    p_digits INTEGER DEFAULT 5
)
RETURNS DECIMAL AS $$
DECLARE
    pip_diff DECIMAL;
BEGIN
    pip_diff := (p_exit - p_entry) * POWER(10, p_digits);
    IF p_direction = 'SELL' THEN
        pip_diff := -pip_diff;
    END IF;
    RETURN pip_diff * p_volume * p_pip_value / pip_diff;  -- Simplified
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ============================================================================
-- VIEWS
-- ============================================================================

-- Daily performance summary
CREATE OR REPLACE VIEW v_daily_performance AS
SELECT
    DATE(tr.executed_at) AS trade_date,
    COUNT(*) AS total_trades,
    COUNT(*) FILTER (WHERE tr.pnl > 0) AS winning_trades,
    COUNT(*) FILTER (WHERE tr.pnl < 0) AS losing_trades,
    COALESCE(SUM(tr.pnl), 0) AS total_pnl,
    COALESCE(AVG(tr.pnl) FILTER (WHERE tr.pnl > 0), 0) AS avg_win,
    COALESCE(AVG(tr.pnl) FILTER (WHERE tr.pnl < 0), 0) AS avg_loss,
    COALESCE(SUM(tr.commission), 0) AS total_commission
FROM trades tr
WHERE tr.status = 'FILLED' AND tr.execution_mode = 'live'
GROUP BY DATE(tr.executed_at)
ORDER BY trade_date DESC;

-- Active setups heatmap
CREATE OR REPLACE VIEW v_setup_performance AS
SELECT
    s.setup_type,
    s.timeframe,
    COUNT(*) AS total_signals,
    COUNT(*) FILTER (WHERE t.id IS NOT NULL) AS executed,
    COUNT(*) FILTER (WHERE t.pnl > 0) AS wins,
    COUNT(*) FILTER (WHERE t.pnl < 0) AS losses,
    ROUND(
        COUNT(*) FILTER (WHERE t.pnl > 0)::NUMERIC /
        NULLIF(COUNT(*) FILTER (WHERE t.id IS NOT NULL), 0) * 100,
        1
    ) AS win_rate_pct,
    AVG(t.pnl) AS avg_pnl
FROM signals s
LEFT JOIN trades t ON t.signal_id = s.id
GROUP BY s.setup_type, s.timeframe
ORDER BY total_signals DESC;

-- Equity curve data
CREATE OR REPLACE VIEW v_equity_curve AS
WITH daily AS (
    SELECT
        DATE(snapshot_at) AS trade_date,
        equity,
        balance,
        closed_pnl,
        open_pnl,
        LAG(equity) OVER (ORDER BY DATE(snapshot_at)) AS prev_equity
    FROM equity_snapshots
)
SELECT
    trade_date,
    equity,
    balance,
    closed_pnl,
    open_pnl,
    equity - COALESCE(prev_equity, equity) AS daily_change,
    (equity - COALESCE(prev_equity, equity)) / NULLIF(prev_equity, 0) * 100 AS daily_return_pct,
    equity - MIN(equity) OVER (ORDER BY trade_date ROWS UNBOUNDED PRECEDING) AS drawdown_from_peak
FROM daily
ORDER BY trade_date DESC;
"""


SEED_SQL = """
-- Sample data for testing (only used with --seed flag)
-- ============================================================================

-- Sample signals
INSERT INTO signals (symbol, direction, setup_type, timeframe, confidence,
    entry_zone, stop_loss, take_profit, risk_reward, market_context, source)
VALUES
    ('EURUSD', 'BUY', 'ORDER_BLOCK', 'H1', 0.82,
     '{"min": 1.0850, "max": 1.0860, "ideal": 1.0855}',
     1.0820,
     '[{"level": 1.0920, "type": "TP1"}, {"level": 1.0960, "type": "TP2"}]',
     1.5,
     '{"session": "LONDON", "trend": "BULLISH", "volatility": "NORMAL"}',
     'smc_pipeline'),
    ('GBPUSD', 'SELL', 'BREAK_OF_STRUCTURE', 'H4', 0.75,
     '{"min": 1.2650, "max": 1.2660, "ideal": 1.2655}',
     1.2700,
     '[{"level": 1.2550, "type": "TP1"}]',
     2.0,
     '{"session": "NY", "trend": "BEARISH", "volatility": "HIGH"}',
     'smc_pipeline'),
    ('USDJPY', 'BUY', 'FVG', 'M15', 0.68,
     '{"min": 149.50, "max": 149.60, "ideal": 149.55}',
     149.20,
     '[{"level": 150.00, "type": "TP1"}]',
     1.2,
     '{"session": "LONDON", "trend": "NEUTRAL", "volatility": "LOW"}',
     'technical_engine');
"""


# ============================================================================
# CONNECTION
# ============================================================================


@dataclass
class DBConfig:
    host: str
    port: int
    database: str
    user: str
    password: str

    @classmethod
    def from_env(cls) -> "DBConfig":
        return cls(
            host=os.getenv("DB_HOST", "localhost"),
            port=int(os.getenv("DB_PORT", "5432")),
            database=os.getenv("DB_NAME", "agentfinance"),
            user=os.getenv("DB_USER", "agentfinance"),
            password=os.getenv("DB_PASSWORD", ""),
        )

    @classmethod
    def from_docker(cls) -> "DBConfig":
        return cls(
            host=os.getenv("DB_HOST", "localhost"),
            port=int(os.getenv("DB_PORT", "5432")),
            database=os.getenv("DB_NAME", "agentfinance"),
            user=os.getenv("DB_USER", "agentfinance"),
            password=os.getenv("DB_PASSWORD", "agentfinance"),
        )

    def connection_string(self) -> str:
        return f"postgresql://{self.user}:{self.password}@{self.host}:{self.port}/{self.database}"


def get_connection(config: DBConfig):
    try:
        import psycopg2

        return psycopg2.connect(
            host=config.host,
            port=config.port,
            database=config.database,
            user=config.user,
            password=config.password,
        )
    except ImportError:
        log.error("psycopg2 not installed. Run: pip install psycopg2-binary")
        return None


# ============================================================================
# COMMANDS
# ============================================================================


def cmd_status(config: DBConfig):
    """Check database connection status."""
    print(f"\n{'═' * 50}")
    print(f"  PostgreSQL Connection Status")
    print(f"{'═' * 50}\n")

    conn = get_connection(config)
    if conn:
        cur = conn.cursor()
        cur.execute("SELECT version();")
        version = cur.fetchone()[0]
        cur.execute("SELECT pg_database_size(%s);", (config.database,))
        size = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM pg_tables WHERE schemaname = 'public';")
        tables = cur.fetchone()[0]

        print_ok(f"Connected to: {config.host}:{config.port}/{config.database}")
        print(f"  PostgreSQL: {version.split(',')[0]}")
        print(f"  DB Size: {size / 1024 / 1024:.1f} MB")
        print(f"  Tables: {tables}")
        cur.close()
        conn.close()
    else:
        print_fail(f"Cannot connect to {config.host}:{config.port}")
        print_info("Options:")
        print(
            "  1. Start PostgreSQL: docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=agentfinance postgres:16"
        )
        print("  2. Use Docker Compose (see docker-compose.yml)")
        print("  3. Install locally and run: sudo systemctl start postgresql")


def cmd_init(config: DBConfig, drop_existing: bool = False):
    """Initialize the database schema."""
    print(f"\n{'═' * 50}")
    print(f"  Initializing Database Schema")
    print(f"{'═' * 50}\n")

    conn = get_connection(config)
    if not conn:
        print_fail("Cannot connect to database")
        return False

    cur = conn.cursor()

    try:
        if drop_existing:
            print_warn("Dropping existing tables...")
            cur.execute("""
                DROP TABLE IF EXISTS equity_snapshots CASCADE;
                DROP TABLE IF EXISTS trades CASCADE;
                DROP TABLE IF EXISTS signals CASCADE;
                DROP TABLE IF EXISTS performance_metrics CASCADE;
                DROP TABLE IF EXISTS session_analysis CASCADE;
                DROP TABLE IF EXISTS ohlcv_data CASCADE;
                DROP TYPE IF EXISTS trade_direction CASCADE;
                DROP TYPE IF EXISTS order_status CASCADE;
                DROP TYPE IF EXISTS setup_type CASCADE;
                DROP TYPE IF EXISTS session_name CASCADE;
                DROP TYPE IF EXISTS timeframe_enum CASCADE;
            """)
            conn.commit()

        # Execute schema
        schema = SCHEMA_SQL.format(timestamp=datetime.now(timezone.utc).isoformat())
        cur.execute(schema)
        conn.commit()

        # Count created tables
        cur.execute("""
            SELECT COUNT(*) FROM pg_tables
            WHERE schemaname = 'public'
            AND tablename NOT LIKE 'pg_%'
            AND tablename NOT LIKE 'sql_%';
        """)
        tables = cur.fetchone()[0]

        print_ok(f"Schema initialized successfully")
        print(f"  Tables created: {tables}")
        print(
            f"  Views created: 3 (v_daily_performance, v_setup_performance, v_equity_curve)"
        )

    except Exception as e:
        print_fail(f"Schema initialization failed: {e}")
        conn.rollback()
        return False
    finally:
        cur.close()
        conn.close()

    return True


def cmd_seed(config: DBConfig):
    """Add sample seed data for testing."""
    print(f"\n{'═' * 50}")
    print(f"  Seeding Sample Data")
    print(f"{'═' * 50}\n")

    conn = get_connection(config)
    if not conn:
        print_fail("Cannot connect to database")
        return False

    cur = conn.cursor()
    try:
        cur.execute(SEED_SQL)
        conn.commit()
        print_ok("Sample data inserted")
    except Exception as e:
        print_fail(f"Seed failed: {e}")
        conn.rollback()
    finally:
        cur.close()
        conn.close()


def cmd_query(config: DBConfig, sql: str):
    """Run a SQL query."""
    conn = get_connection(config)
    if not conn:
        print_fail("Cannot connect to database")
        return

    cur = conn.cursor()
    try:
        cur.execute(sql)
        if cur.description:
            rows = cur.fetchall()
            cols = [d[0] for d in cur.description]
            print(f"\n{' Col ':─<30} " * len(cols))
            header = "  ".join(f"{c:<30}" for c in cols)
            print(header)
            print("─" * 80)
            for row in rows[:20]:
                print("  ".join(f"{str(v)[:30]:<30}" for v in row))
            if len(rows) > 20:
                print(f"\n  ... {len(rows) - 20} more rows")
            print(f"\n  {len(rows)} rows returned")
        else:
            print_ok(f"Query executed, {cur.rowcount} rows affected")
    except Exception as e:
        print_fail(f"Query failed: {e}")
    finally:
        cur.close()
        conn.close()


# ============================================================================
# DOCKER COMPOSE FOR POSTGRES
# ============================================================================

DOCKER_COMPOSE_PG = """
version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: agentfinance-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: agentfinance
      POSTGRES_USER: agentfinance
      POSTGRES_PASSWORD: {password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agentfinance"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
"""


def cmd_docker_compose():
    """Generate docker-compose for PostgreSQL."""
    import uuid

    password = str(uuid.uuid4())[:16]
    print_info("Generating docker-compose.yml for PostgreSQL...")

    content = DOCKER_COMPOSE_PG.format(password=password)
    path = PROJECT_ROOT / "docker-compose.pg.yml"
    with open(path, "w") as f:
        f.write(content)

    print_ok(f"Created {path}")
    print_info(f"Generated password: {password}")
    print_info("Save this password! Add to your .env:")
    print(f"  DB_PASSWORD={password}")


# ============================================================================
# MAIN
# ============================================================================


def main():
    parser = argparse.ArgumentParser(description="AgentFinance PostgreSQL Setup")
    parser.add_argument("--status", action="store_true", help="Check connection status")
    parser.add_argument("--init", action="store_true", help="Initialize schema")
    parser.add_argument("--seed", action="store_true", help="Add seed data")
    parser.add_argument(
        "--drop", action="store_true", help="Drop existing tables first"
    )
    parser.add_argument(
        "--docker-compose",
        action="store_true",
        help="Generate Docker Compose for PostgreSQL",
    )
    parser.add_argument("--query", type=str, help="Run SQL query")
    parser.add_argument(
        "--env", choices=["docker", "local"], default="local", help="Connection mode"
    )
    args = parser.parse_args()

    config = DBConfig.from_env() if args.env == "local" else DBConfig.from_docker()

    if args.docker_compose:
        cmd_docker_compose()
        return

    if args.status:
        cmd_status(config)
        return

    if args.init:
        success = cmd_init(config, drop_existing=args.drop)
        sys.exit(0 if success else 1)
        return

    if args.seed:
        cmd_seed(config)
        return

    if args.query:
        cmd_query(config, args.query)
        return

    # Default: interactive
    print(f"\n{'═' * 50}")
    print(f"  AgentFinance Database Setup")
    print(f"{'═' * 50}\n")
    print("Usage:")
    print("  python3 setup_database.py --status         # Check connection")
    print("  python3 setup_database.py --init           # Create schema")
    print("  python3 setup_database.py --init --drop   # Recreate schema")
    print("  python3 setup_database.py --seed           # Add sample data")
    print("  python3 setup_database.py --docker-compose # Generate Docker Compose")
    print()
    print(f"Connection: {config.host}:{config.port}/{config.database}")
    print()


if __name__ == "__main__":
    main()
